# Generated by Django 4.1.4 on 2022-12-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categoy',
            new_name='category',
        ),
    ]
